version: "3"

env:
  NATS_PORT: 4222

tasks:
  # The `build:` tasks below are used together for production builds of a project
  build:templ:
    cmds:
      - go tool templ generate
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"

  build:web:
    cmds:
      - go run cmd/web/build/main.go
    sources:
      - "**/*.css"
      - "**/*.ts"
      - "**/*.js"
      - exclude: "**/static/**/*.{css,ts,js}"
    generates:
      - "./app/features/*/web/static/**"

  build:
    cmds:
      - go build -tags=prod -o bin/main ./cmd/web
    deps:
      - build:templ
      - build:web

  # Use this task to debug with the delve debugger
  debug:
    cmds:
      - go tool dlv exec ./bin/main
    deps:
      - build

  # Use this task to download latest version of client libs
  download:
    cmds:
      - go run cmd/downloader/main.go


  # The `live:` tasks below are used together for development builds and will live-reload the server
  live:templ:
    cmds:
      - go tool templ generate -watch

  live:web:
    cmds:
      - go run cmd/web/build/main.go -watch

  live:server:
    cmds:
      - |
        go tool air  \
         -build.cmd "go build -tags=dev -o tmp/bin/main ./cmd/web" \
         -build.bin "tmp/bin/main" \
         -build.exclude_dir "data,node_modules" \
         -build.include_ext "go,templ" \
         -misc.clean_on_exit "true"

  live:
    deps:
      - live:templ
      - live:web
      - live:server

  run:
    cmds:
      - ./bin/main
    deps:
      - build

  clean:static:
    cmds:
      - find ./app/features/*/web/static -mindepth 1 -maxdepth 1 ! -name "assets" ! -name "datastar" -exec rm -rf {} +

  fmt:go:
    cmds:
      - go fmt ./...
      - go mod tidy
    sources:
      - "**/*.go"
      - exclude: "**/*_templ.go"

  fmt:templ:
    cmds:
      - go tool templ fmt .
    sources:
      - "**/*.templ"

  fmt:ts:
    cmds:
      - pnpm prettier --write "**/*.{ts,js}"
    sources:
      - "**/*.ts"
      - "**/*.js"
      - exclude: "**/static/**/*.{ts,js}"

  fmt:css:
    cmds:
      - pnpm prettier --write "**/*.css"
    sources:
      - "**/*.css"
      - exclude: "**/static/**/*.css"

  fmt:
    deps:
      - fmt:go
      - fmt:templ
      - fmt:ts
      - fmt:css

  default:
    cmds:
      - task: live
